### ISSUE TITLE
Bolg link is not Found

### ISSUE THREAD

**Issue by wangzhangup** [yukimasano/self-label#1]
Current link is
http://www.robots.ox.ac.uk/~vgg/blogs/elf-labelling-via-simultaneous-clustering-and-representation-learning.html
Correct one is
 http://www.robots.ox.ac.uk/~vgg/blog/self-labelling-via-simultaneous-clustering-and-representation-learning.html

**Comment by yukimasano** [comment]
Thanks! fixed it.
