### ISSUE TITLE
 how to configure number of clustering heads T, if clustering is priority

### ISSUE THREAD

**Issue by ksulima** [yukimasano/self-label#12]
Hi,

You say in a paper 3.5 `Since our main objective is to use clustering to learn a good data representation Φ, we consider a multi-task setting in which the same representation is shared among several different clustering tasks, which can potentially capture different and complementary clustering axis`

What if my main objective is to receive meaningful clusters. I would like to train model on my own unlabeled, rather messy dataset and then clean dataset from particular images filtering out some clusters. 
Would you recommend to set number of heads T =1 in that case?

**Comment by yukimasano** [comment]
Hey!
If the main objective is to cluster images (as opposed to learning representations), you could try something I mentioned here: https://github.com/yukimasano/self-label/issues/11 (i.e. start with a pretrained model and only reset the last layer). And yes, probably starting with one head makes most sense. 

Later you can also play around with replacing the head (currently a linear layer) with a MLP and see if it further improves / makes more diverse heads.

**Comment by yukimasano** [comment]
Good luck!

**Comment by ksulima** [comment]
Thanks for a quick response. I will follow your advice.
