### ISSUE TITLE
Provide a concise requirements.txt

### ISSUE THREAD

**Issue by bespoke-code** [yukimasano/self-label#15]
Hi @yukimasano and @mayank010698 ,

Could you please provide a `requirements.txt` file for everyone interested to set up the project painlessly?
Your README.md suggests the following:

> Requirements
Python >3.6
PyTorch > 1.0
CUDA
Numpy, SciPy
(optional:) TensorboardX

Here's a configuration which successfully runs the `scripts/eval-resnet.sh` script with the `resnet-10x3k` model:
```pip-chill==1.0.0
scipy==1.5.2
tensorboardx==2.1
torch==1.6.0
torchvision~=0.7.0
numpy~=1.19.2
Pillow~=7.2.0
```

Providing a requirements.txt file can save a lot of debugging hours finding which exact version of `torch (> 1.0.0)` and `torchvision` works.

Thank you in advance!

**Comment by bespoke-code** [comment]
Fixed the issue I previously mentioned (accidentally deleted the 0 in `eval-resnet.sh: line 5` so the 10 became a 1, which is incompatible with the aptly named `resnet-10x3k.pth`).

Created a PR to include the requirements.txt.

**Comment by yukimasano** [comment]
Hi I'll add it to the readme :) thanks!
