### ISSUE TITLE
Reproducing Results

### ISSUE THREAD

**Issue by bhiziroglu** [yukimasano/self-label#2]
Hello,

I am trying to reproduce the reported results for ImageNet using AlexNet. I have simply cloned the repository and run alexnet.sh script. I am using 4 Nvidia RTX 2080ti GPUs. 

In the paper, for the label optimization step, it is stated that "convergence is reached within 2 minutes on ImageNet when computed on a GPU". In my case, it takes 5 days and the program throws an out-of-memory error after that. What kind of GPUs have you used during the training?

Also, as a follow-up: I was wondering if it is possible to share the CIFAR code since it is easier to run and reproduce the results?

Thank you.

**Comment by yukimasano** [comment]
Hi, 
the Sinkhorn Knopp operation should finish within 2minutes when run on a GPU, not the main code. The gpu code uses the last N-1 GPUs for accumulating the activations, so ideally run this on larger GPUs (e.g. 24GB memory). That being said you could try to reduce K from 3000 to 1000 (it'll require 33% less memory) and I will upload the cifar code asap.

**Comment by yukimasano** [comment]
Hi, I've added a version that should be easily runnable one normal machine, checkout scripts/alexnet-cpu.sh. 

Apart from that I've added the CIFAR code. Thanks for the patience!
