### ISSUE TITLE
customize dataset

### ISSUE THREAD

**Issue by sulaiman1988** [yukimasano/self-label#26]
how we can evaluate with customized dataset?

**Comment by yukimasano** [comment]
HI there, can you be more specific? What do you mean by evaluate?

**Comment by ran66666** [comment]
I want to train my dataset without labels only images. How can I customized the dataset?

**Comment by yukimasano** [comment]
Hi, simply make a folder containing the images and then replace the directory to imagenet to your folder.

**Comment by ran66666** [comment]
Thanks for your reply.
