### ISSUE TITLE
divide by zero encountered in true_divide in custom dataset

### ISSUE THREAD

**Issue by ran66666** [yukimasano/self-label#27]
Hi,

I am trying to use your algorithm using my custom dataset.During training
/python main.py --batch-size 4 --imagenet-path /home/ran/ship_sea_data/images/ --workers 1
, except a 'divide by zero' error. I check the list but no zero in list. What causes it？

![2023-04-13 10-28-11 的屏幕截图](https://user-images.githubusercontent.com/34015134/231640968-8c900491-0daf-41a1-8fa1-93b37fc37e19.png)

**Comment by ran66666** [comment]
![2023-04-13 16-20-07 的屏幕截图](https://user-images.githubusercontent.com/34015134/231698883-fc36024a-73f0-4323-b627-618688eaa3d6.png)


I found the problem is that the maximum value is out of bounds. What is the reason for this?

**Comment by ran66666** [comment]
![2023-04-13 16-37-15 的屏幕截图](https://user-images.githubusercontent.com/34015134/231703885-b11112ea-e863-46bb-a0fe-1b8a5fb009c9.png)
I revise the code in line 117 to catch zero in self.PS.
And then i call 
/python main.py --batch-size 4 --imagenet-path /home/ran/ship_sea_data/images/ --workers 1
and get result like follow picture:


![2023-04-13 16-36-34 的屏幕截图](https://user-images.githubusercontent.com/34015134/231704502-622abdfb-3eb0-4f48-9e6c-ea15eab48afe.png)
What cause the zero in self.PS? I have correct the data in my dataset,every image is not damaged.

**Comment by yukimasano** [comment]
Hi, it could be that the initialise size of PS is not equal to the entries that got used to fill it (e.g. when using drop_last=True, ie the last batch is dropped).

There's also some instabilities, for a more stable version, check this logarithmic version here: 
https://github.com/facebookresearch/selavi 

or check the way it's implemented in SwAV: https://github.com/facebookresearch/swav

**Comment by ran66666** [comment]
Thank you for your response . It's helpful for my work.
