### ISSUE TITLE
How to type 🆕✅🎉 ？

### ISSUE THREAD

**Issue by PkuRainBow** [yukimasano/self-label#4]
Really nice work.
I have a small question on how to print cute symbols like 🆕✅🎉.

Thanks

**Comment by yukimasano** [comment]
Hey there :). No special magic, just copy and paste like it was any other character. 
You can search for emojis e.g. here: https://getemoji.com/
PS: in python3 you _could_ even do something like `😄 = 3`, it's just like an alphabet character.
