### ISSUE TITLE
knn_dim = 256*6*6

### ISSUE THREAD

**Issue by mayank010698** [yukimasano/self-label#6]
in cifar.py `knn_dim = 4096` . However, after last conv-layer, dim is 9216. Shouldn't it be 9216 then ?

**Comment by yukimasano** [comment]
good points, for AlexNet we actually use the representation after the FC layers, which then is 4096. Fixed this here: https://github.com/yukimasano/self-label/commit/7700246e1040b8cf3efce0eb2fb8f61a7614703b 
so hopefully it should work fine when using CIFAR & AlexNet. Let me know if it doesn't :)
